---
- name: Home work 3
  hosts: carrier
  become: true
  roles:
    - 3_task
  tasks:
    - name: Display Configuration Variables
      ansible.builtin.debug:
        msg:
          - "monitoring_url: {{ monitoring_url }}" # monitoring url including port
