---
- name: Обновление apt кэша
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Установка зависимостей
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Добавление GPG ключа Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: Добавление репозитория Docker
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else
      ('arm64' if ansible_architecture == 'aarch64' else ansible_architecture) }}
      signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  become: true

- name: Обновление apt кэша после добавления репозитория
  ansible.builtin.apt:
    update_cache: true

- name: Установка Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Запуск и активация сервиса Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Установка Docker Compose
  ansible.builtin.apt:
    name:
      - docker-compose-plugin
      - docker-compose
    state: present
