---
- name: Wait for Grafana readiness
  ansible.builtin.wait_for:
    port: 3000
    host: "{{ ansible_default_ipv4.address }}"
    delay: 5
    timeout: 60

- name: Wait for Galera readiness
  ansible.builtin.wait_for:
    port: 3306
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 120
