---
- name: Установка PyMySQL для работы с MySQL
  ansible.builtin.package:
    name: python3-pymysql
    state: present
  become: true

- name: Создание директории проекта
  ansible.builtin.file:
    path: "{{ project_dir }}"
    mode: '0750'
    state: directory

- name: Создание директорий для конфигурации
  ansible.builtin.file:
    path: "{{ project_dir }}/{{ item }}"
    mode: '0755'
    state: directory
  loop:
    - galera_config
    - haproxy_config
    - mysql_init
    - backup

- name: Проверка существования Galera кластера
  community.docker.docker_container_info:
    name: galera-node1
  register: galera_cluster_status
  failed_when: false

- name: Создание конфигурации Galera
  ansible.builtin.template:
    src: galera.cnf.j2
    dest: "{{ project_dir }}/galera_config/galera.cnf"
    mode: '0644'
  register: galera_config_result

- name: Создание конфигурации HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ project_dir }}/haproxy_config/haproxy.cfg"
    mode: '0644'
  register: haproxy_config_result

- name: Миграция данных из предыдущих установок
  ansible.builtin.import_tasks: migrate_data.yml

- name: Создание инициализационного SQL скрипта
  ansible.builtin.template:
    src: init.sql.j2
    dest: "{{ project_dir }}/mysql_init/init.sql"
    mode: '0644'

- name: Остановка предыдущих контейнеров (только при изменении конфигурации)
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ ansible_user }}/wordpress-docker"
    - "/home/{{ ansible_user }}/wordpress-cluster"
  failed_when: false
  when: >
    not galera_cluster_status.exists or
    galera_config_result.changed or
    haproxy_config_result.changed

- name: Создание Docker Compose файла
  ansible.builtin.template:
    src: docker-compose-galera.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"
    mode: '0644'
  register: compose_config_result

- name: Запуск или обновление Galera Cluster
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
  register: galera_deployment_result

- name: Ожидание готовности первого узла Galera
  ansible.builtin.wait_for:
    port: 3306
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 120

- name: Проверка состояния кластера
  community.mysql.mysql_query:
    login_host: "{{ ansible_default_ipv4.address }}"
    login_port: 3306
    login_user: root
    login_password: "{{ db_pass }}"
    query: "SHOW STATUS LIKE 'wsrep_cluster_size'"
  register: cluster_status
  retries: 5
  delay: 10
  until: cluster_status is not failed

- name: Восстановление данных WordPress (если есть бэкап)
  community.mysql.mysql_db:
    login_host: "{{ ansible_default_ipv4.address }}"
    login_port: 3306
    login_user: root
    login_password: "{{ db_pass }}"
    name: "{{ wordpress_db_name }}"
    state: import
    target: "{{ project_dir }}/backup/wordpress_backup.sql"
  when:
    - backup_exists.stat.exists
    - backup_exists.stat.size > 100
    - galera_deployment_result.changed
  register: restore_result
  failed_when: false

- name: Проверка и запуск мониторинга
  ansible.builtin.import_tasks: setup_monitoring.yml

- name: Вывод информации о кластере
  ansible.builtin.debug:
    msg: |
      Galera Cluster размер: {{ cluster_status.query_result[0][0].Value if cluster_status.query_result else 'unknown' }}
      HAProxy статистика: http://{{ ansible_default_ipv4.address }}:{{ haproxy_stats_port }}/stats
      WordPress: http://{{ ansible_default_ipv4.address }}:{{ wordpress_port }}
      Мониторинг: {{ monitoring_url }}
