---
- name: Проверка состояния мониторинга
  community.docker.docker_container_info:
    name: prometheus
  register: monitoring_status
  failed_when: false

- name: Обновление конфигурации Prometheus для Galera
  ansible.builtin.template:
    src: prometheus-galera.yml.j2
    dest: "/home/{{ ansible_user }}/monitoring/prometheus/prometheus.yml"
    mode: '0644'
  register: prometheus_config_update
  when: monitoring_status.exists

- name: Перезапуск Prometheus при изменении конфигурации
  community.docker.docker_container:
    name: prometheus
    restart: true
  when:
    - monitoring_status.exists
    - prometheus_config_update.changed

- name: Запуск мониторинга если не запущен
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/monitoring"
    state: present
  when: not monitoring_status.exists
  register: monitoring_deployment

- name: Ожидание готовности Grafana
  ansible.builtin.wait_for:
    port: 3000
    host: "{{ ansible_default_ipv4.address }}"
    delay: 5
    timeout: 60
